from __future__ import annotations

import hashlib
import math
from collections import Counter

from proofrag.text import tokenize


class HashingEmbedder:
    """Deterministic local embedding baseline with no model download.

    The production extension point is intentionally narrow: replace this class with
    a dense embedding provider while keeping the repository and retriever contracts.
    The hashing baseline makes the prototype reproducible and usable offline.
    """

    def __init__(self, dimensions: int = 384) -> None:
        self.dimensions = dimensions

    def embed(self, text: str) -> list[float]:
        vector = [0.0] * self.dimensions
        counts = Counter(tokenize(text))
        for token, count in counts.items():
            digest = hashlib.blake2b(token.encode("utf-8"), digest_size=8).digest()
            raw = int.from_bytes(digest, "big")
            index = raw % self.dimensions
            sign = -1.0 if raw & 1 else 1.0
            vector[index] += sign * (1.0 + math.log(count))
        magnitude = math.sqrt(sum(value * value for value in vector))
        if magnitude:
            return [value / magnitude for value in vector]
        return vector

    @staticmethod
    def cosine(left: list[float], right: list[float]) -> float:
        if len(left) != len(right):
            return 0.0
        # Inputs generated by this class are already normalized.
        return max(0.0, sum(a * b for a, b in zip(left, right, strict=True)))

